export SHOP_API_SMTP_HOST=smtp.gmail.com
export SHOP_API_SMTP_PORT=587
export SHOP_API_SMTP_USERNAME=your_email_address@gmail.com
export SHOP_API_SMTP_PASSWORD=your_email_password
export SHOP_DB_HOST=localhost